### ISSUE TITLE
vagrantユーザー作成

### ISSUE THREAD

**Issue by Jun1shr** [oyama919/vagrant-wordpress#10]
vagrantユーザー作成
公開鍵を設定して、鍵認証でsshの設定

**Comment by oyama919** [comment]
```
vagrant ssh
useradd username
```

**Comment by oyama919** [comment]
Vagrantfile
`config.ssh.username = "masaki(ユーザ名)"`

**Comment by Jun1shr** [comment]
ssh-keygen→ローカルで鍵を作成する
vagrant ssh
sudo -s
useradd menta
visudo →mentaユーザーをノーパスワードにする
menta ALL=NOPASSWD: ALL　を追記
sudo su - menta→mentaユーザーになる
mkdir .ssh
vi .ssh/authorized_keys →公開鍵を指定
chmod 700 ~/.ssh
chmod 600 .ssh/authorized_keys
exit
ssh -i ~/.ssh/menta menta@192.168.33.14 


http://javatechnology.net/service/sudo-su-hyphen/
